package com.springboot.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusinessCustomerHistoryInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public BusinessCustomerHistoryInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Integer value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Integer value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Integer value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Integer value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Integer> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Integer> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNull() {
            addCriterion("business_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNotNull() {
            addCriterion("business_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdEqualTo(Integer value) {
            addCriterion("business_id =", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotEqualTo(Integer value) {
            addCriterion("business_id <>", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThan(Integer value) {
            addCriterion("business_id >", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_id >=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThan(Integer value) {
            addCriterion("business_id <", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThanOrEqualTo(Integer value) {
            addCriterion("business_id <=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIn(List<Integer> values) {
            addCriterion("business_id in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotIn(List<Integer> values) {
            addCriterion("business_id not in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdBetween(Integer value1, Integer value2) {
            addCriterion("business_id between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotBetween(Integer value1, Integer value2) {
            addCriterion("business_id not between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInstallAddressIsNull() {
            addCriterion("install_address is null");
            return (Criteria) this;
        }

        public Criteria andInstallAddressIsNotNull() {
            addCriterion("install_address is not null");
            return (Criteria) this;
        }

        public Criteria andInstallAddressEqualTo(String value) {
            addCriterion("install_address =", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressNotEqualTo(String value) {
            addCriterion("install_address <>", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressGreaterThan(String value) {
            addCriterion("install_address >", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressGreaterThanOrEqualTo(String value) {
            addCriterion("install_address >=", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressLessThan(String value) {
            addCriterion("install_address <", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressLessThanOrEqualTo(String value) {
            addCriterion("install_address <=", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressLike(String value) {
            addCriterion("install_address like", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressNotLike(String value) {
            addCriterion("install_address not like", value, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressIn(List<String> values) {
            addCriterion("install_address in", values, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressNotIn(List<String> values) {
            addCriterion("install_address not in", values, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressBetween(String value1, String value2) {
            addCriterion("install_address between", value1, value2, "installAddress");
            return (Criteria) this;
        }

        public Criteria andInstallAddressNotBetween(String value1, String value2) {
            addCriterion("install_address not between", value1, value2, "installAddress");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("order_number is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("order_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(String value) {
            addCriterion("order_number =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(String value) {
            addCriterion("order_number <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(String value) {
            addCriterion("order_number >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(String value) {
            addCriterion("order_number >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(String value) {
            addCriterion("order_number <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(String value) {
            addCriterion("order_number <=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLike(String value) {
            addCriterion("order_number like", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotLike(String value) {
            addCriterion("order_number not like", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIn(List<String> values) {
            addCriterion("order_number in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotIn(List<String> values) {
            addCriterion("order_number not in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberBetween(String value1, String value2) {
            addCriterion("order_number between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(String value1, String value2) {
            addCriterion("order_number not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeIsNull() {
            addCriterion("order_accept_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeIsNotNull() {
            addCriterion("order_accept_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeEqualTo(Date value) {
            addCriterion("order_accept_time =", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeNotEqualTo(Date value) {
            addCriterion("order_accept_time <>", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeGreaterThan(Date value) {
            addCriterion("order_accept_time >", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_accept_time >=", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeLessThan(Date value) {
            addCriterion("order_accept_time <", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_accept_time <=", value, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeIn(List<Date> values) {
            addCriterion("order_accept_time in", values, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeNotIn(List<Date> values) {
            addCriterion("order_accept_time not in", values, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeBetween(Date value1, Date value2) {
            addCriterion("order_accept_time between", value1, value2, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderAcceptTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_accept_time not between", value1, value2, "orderAcceptTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeIsNull() {
            addCriterion("order_return_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeIsNotNull() {
            addCriterion("order_return_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeEqualTo(Date value) {
            addCriterion("order_return_time =", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotEqualTo(Date value) {
            addCriterion("order_return_time <>", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeGreaterThan(Date value) {
            addCriterion("order_return_time >", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_return_time >=", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeLessThan(Date value) {
            addCriterion("order_return_time <", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_return_time <=", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeIn(List<Date> values) {
            addCriterion("order_return_time in", values, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotIn(List<Date> values) {
            addCriterion("order_return_time not in", values, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeBetween(Date value1, Date value2) {
            addCriterion("order_return_time between", value1, value2, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_return_time not between", value1, value2, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andLoadModeIsNull() {
            addCriterion("load_mode is null");
            return (Criteria) this;
        }

        public Criteria andLoadModeIsNotNull() {
            addCriterion("load_mode is not null");
            return (Criteria) this;
        }

        public Criteria andLoadModeEqualTo(String value) {
            addCriterion("load_mode =", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeNotEqualTo(String value) {
            addCriterion("load_mode <>", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeGreaterThan(String value) {
            addCriterion("load_mode >", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeGreaterThanOrEqualTo(String value) {
            addCriterion("load_mode >=", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeLessThan(String value) {
            addCriterion("load_mode <", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeLessThanOrEqualTo(String value) {
            addCriterion("load_mode <=", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeLike(String value) {
            addCriterion("load_mode like", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeNotLike(String value) {
            addCriterion("load_mode not like", value, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeIn(List<String> values) {
            addCriterion("load_mode in", values, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeNotIn(List<String> values) {
            addCriterion("load_mode not in", values, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeBetween(String value1, String value2) {
            addCriterion("load_mode between", value1, value2, "loadMode");
            return (Criteria) this;
        }

        public Criteria andLoadModeNotBetween(String value1, String value2) {
            addCriterion("load_mode not between", value1, value2, "loadMode");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIsNull() {
            addCriterion("business_number is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIsNotNull() {
            addCriterion("business_number is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberEqualTo(String value) {
            addCriterion("business_number =", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotEqualTo(String value) {
            addCriterion("business_number <>", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThan(String value) {
            addCriterion("business_number >", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThanOrEqualTo(String value) {
            addCriterion("business_number >=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThan(String value) {
            addCriterion("business_number <", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThanOrEqualTo(String value) {
            addCriterion("business_number <=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLike(String value) {
            addCriterion("business_number like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotLike(String value) {
            addCriterion("business_number not like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIn(List<String> values) {
            addCriterion("business_number in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotIn(List<String> values) {
            addCriterion("business_number not in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberBetween(String value1, String value2) {
            addCriterion("business_number between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotBetween(String value1, String value2) {
            addCriterion("business_number not between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBandWidthIsNull() {
            addCriterion("band_width is null");
            return (Criteria) this;
        }

        public Criteria andBandWidthIsNotNull() {
            addCriterion("band_width is not null");
            return (Criteria) this;
        }

        public Criteria andBandWidthEqualTo(String value) {
            addCriterion("band_width =", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotEqualTo(String value) {
            addCriterion("band_width <>", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthGreaterThan(String value) {
            addCriterion("band_width >", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthGreaterThanOrEqualTo(String value) {
            addCriterion("band_width >=", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLessThan(String value) {
            addCriterion("band_width <", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLessThanOrEqualTo(String value) {
            addCriterion("band_width <=", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLike(String value) {
            addCriterion("band_width like", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotLike(String value) {
            addCriterion("band_width not like", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthIn(List<String> values) {
            addCriterion("band_width in", values, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotIn(List<String> values) {
            addCriterion("band_width not in", values, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthBetween(String value1, String value2) {
            addCriterion("band_width between", value1, value2, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotBetween(String value1, String value2) {
            addCriterion("band_width not between", value1, value2, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdIsNull() {
            addCriterion("unicom_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdIsNotNull() {
            addCriterion("unicom_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdEqualTo(String value) {
            addCriterion("unicom_customer_id =", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdNotEqualTo(String value) {
            addCriterion("unicom_customer_id <>", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdGreaterThan(String value) {
            addCriterion("unicom_customer_id >", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("unicom_customer_id >=", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdLessThan(String value) {
            addCriterion("unicom_customer_id <", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("unicom_customer_id <=", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdLike(String value) {
            addCriterion("unicom_customer_id like", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdNotLike(String value) {
            addCriterion("unicom_customer_id not like", value, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdIn(List<String> values) {
            addCriterion("unicom_customer_id in", values, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdNotIn(List<String> values) {
            addCriterion("unicom_customer_id not in", values, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdBetween(String value1, String value2) {
            addCriterion("unicom_customer_id between", value1, value2, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andUnicomCustomerIdNotBetween(String value1, String value2) {
            addCriterion("unicom_customer_id not between", value1, value2, "unicomCustomerId");
            return (Criteria) this;
        }

        public Criteria andTransactTypeIsNull() {
            addCriterion("transact_type is null");
            return (Criteria) this;
        }

        public Criteria andTransactTypeIsNotNull() {
            addCriterion("transact_type is not null");
            return (Criteria) this;
        }

        public Criteria andTransactTypeEqualTo(String value) {
            addCriterion("transact_type =", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeNotEqualTo(String value) {
            addCriterion("transact_type <>", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeGreaterThan(String value) {
            addCriterion("transact_type >", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeGreaterThanOrEqualTo(String value) {
            addCriterion("transact_type >=", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeLessThan(String value) {
            addCriterion("transact_type <", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeLessThanOrEqualTo(String value) {
            addCriterion("transact_type <=", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeLike(String value) {
            addCriterion("transact_type like", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeNotLike(String value) {
            addCriterion("transact_type not like", value, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeIn(List<String> values) {
            addCriterion("transact_type in", values, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeNotIn(List<String> values) {
            addCriterion("transact_type not in", values, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeBetween(String value1, String value2) {
            addCriterion("transact_type between", value1, value2, "transactType");
            return (Criteria) this;
        }

        public Criteria andTransactTypeNotBetween(String value1, String value2) {
            addCriterion("transact_type not between", value1, value2, "transactType");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdIsNull() {
            addCriterion("package_name_id is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdIsNotNull() {
            addCriterion("package_name_id is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdEqualTo(Integer value) {
            addCriterion("package_name_id =", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdNotEqualTo(Integer value) {
            addCriterion("package_name_id <>", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdGreaterThan(Integer value) {
            addCriterion("package_name_id >", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("package_name_id >=", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdLessThan(Integer value) {
            addCriterion("package_name_id <", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdLessThanOrEqualTo(Integer value) {
            addCriterion("package_name_id <=", value, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdIn(List<Integer> values) {
            addCriterion("package_name_id in", values, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdNotIn(List<Integer> values) {
            addCriterion("package_name_id not in", values, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdBetween(Integer value1, Integer value2) {
            addCriterion("package_name_id between", value1, value2, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andPackageNameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("package_name_id not between", value1, value2, "packageNameId");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNull() {
            addCriterion("service_price is null");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNotNull() {
            addCriterion("service_price is not null");
            return (Criteria) this;
        }

        public Criteria andServicePriceEqualTo(String value) {
            addCriterion("service_price =", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotEqualTo(String value) {
            addCriterion("service_price <>", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThan(String value) {
            addCriterion("service_price >", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThanOrEqualTo(String value) {
            addCriterion("service_price >=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThan(String value) {
            addCriterion("service_price <", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThanOrEqualTo(String value) {
            addCriterion("service_price <=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLike(String value) {
            addCriterion("service_price like", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotLike(String value) {
            addCriterion("service_price not like", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceIn(List<String> values) {
            addCriterion("service_price in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotIn(List<String> values) {
            addCriterion("service_price not in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceBetween(String value1, String value2) {
            addCriterion("service_price between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotBetween(String value1, String value2) {
            addCriterion("service_price not between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdIsNull() {
            addCriterion("customer_manager_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdIsNotNull() {
            addCriterion("customer_manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdEqualTo(Integer value) {
            addCriterion("customer_manager_id =", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdNotEqualTo(Integer value) {
            addCriterion("customer_manager_id <>", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdGreaterThan(Integer value) {
            addCriterion("customer_manager_id >", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_manager_id >=", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdLessThan(Integer value) {
            addCriterion("customer_manager_id <", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_manager_id <=", value, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdIn(List<Integer> values) {
            addCriterion("customer_manager_id in", values, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdNotIn(List<Integer> values) {
            addCriterion("customer_manager_id not in", values, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_manager_id between", value1, value2, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andCustomerManagerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_manager_id not between", value1, value2, "customerManagerId");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneIsNull() {
            addCriterion("manager_phone is null");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneIsNotNull() {
            addCriterion("manager_phone is not null");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneEqualTo(String value) {
            addCriterion("manager_phone =", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneNotEqualTo(String value) {
            addCriterion("manager_phone <>", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneGreaterThan(String value) {
            addCriterion("manager_phone >", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("manager_phone >=", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneLessThan(String value) {
            addCriterion("manager_phone <", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneLessThanOrEqualTo(String value) {
            addCriterion("manager_phone <=", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneLike(String value) {
            addCriterion("manager_phone like", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneNotLike(String value) {
            addCriterion("manager_phone not like", value, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneIn(List<String> values) {
            addCriterion("manager_phone in", values, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneNotIn(List<String> values) {
            addCriterion("manager_phone not in", values, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneBetween(String value1, String value2) {
            addCriterion("manager_phone between", value1, value2, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andManagerPhoneNotBetween(String value1, String value2) {
            addCriterion("manager_phone not between", value1, value2, "managerPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdIsNull() {
            addCriterion("business_manager_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdIsNotNull() {
            addCriterion("business_manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdEqualTo(Integer value) {
            addCriterion("business_manager_id =", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdNotEqualTo(Integer value) {
            addCriterion("business_manager_id <>", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdGreaterThan(Integer value) {
            addCriterion("business_manager_id >", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_manager_id >=", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdLessThan(Integer value) {
            addCriterion("business_manager_id <", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdLessThanOrEqualTo(Integer value) {
            addCriterion("business_manager_id <=", value, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdIn(List<Integer> values) {
            addCriterion("business_manager_id in", values, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdNotIn(List<Integer> values) {
            addCriterion("business_manager_id not in", values, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdBetween(Integer value1, Integer value2) {
            addCriterion("business_manager_id between", value1, value2, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andBusinessManagerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("business_manager_id not between", value1, value2, "businessManagerId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("order_status like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("order_status not like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<String> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<String> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Integer value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Integer value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Integer value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Integer value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Integer> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Integer> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNull() {
            addCriterion("data_status is null");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNotNull() {
            addCriterion("data_status is not null");
            return (Criteria) this;
        }

        public Criteria andDataStatusEqualTo(String value) {
            addCriterion("data_status =", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotEqualTo(String value) {
            addCriterion("data_status <>", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThan(String value) {
            addCriterion("data_status >", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThanOrEqualTo(String value) {
            addCriterion("data_status >=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThan(String value) {
            addCriterion("data_status <", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThanOrEqualTo(String value) {
            addCriterion("data_status <=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLike(String value) {
            addCriterion("data_status like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotLike(String value) {
            addCriterion("data_status not like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusIn(List<String> values) {
            addCriterion("data_status in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotIn(List<String> values) {
            addCriterion("data_status not in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusBetween(String value1, String value2) {
            addCriterion("data_status between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotBetween(String value1, String value2) {
            addCriterion("data_status not between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdIsNull() {
            addCriterion("edit_operator_id is null");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdIsNotNull() {
            addCriterion("edit_operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdEqualTo(Integer value) {
            addCriterion("edit_operator_id =", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdNotEqualTo(Integer value) {
            addCriterion("edit_operator_id <>", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdGreaterThan(Integer value) {
            addCriterion("edit_operator_id >", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("edit_operator_id >=", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdLessThan(Integer value) {
            addCriterion("edit_operator_id <", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("edit_operator_id <=", value, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdIn(List<Integer> values) {
            addCriterion("edit_operator_id in", values, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdNotIn(List<Integer> values) {
            addCriterion("edit_operator_id not in", values, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("edit_operator_id between", value1, value2, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andEditOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("edit_operator_id not between", value1, value2, "editOperatorId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIsNull() {
            addCriterion("business_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIsNotNull() {
            addCriterion("business_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdEqualTo(Integer value) {
            addCriterion("business_customer_id =", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotEqualTo(Integer value) {
            addCriterion("business_customer_id <>", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdGreaterThan(Integer value) {
            addCriterion("business_customer_id >", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_customer_id >=", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdLessThan(Integer value) {
            addCriterion("business_customer_id <", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("business_customer_id <=", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIn(List<Integer> values) {
            addCriterion("business_customer_id in", values, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotIn(List<Integer> values) {
            addCriterion("business_customer_id not in", values, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("business_customer_id between", value1, value2, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("business_customer_id not between", value1, value2, "businessCustomerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_customer_history_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}