package com.springboot.crm.entity;

import java.io.Serializable;
import java.util.Date;

public class CustomerHistoryInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.previous_name
     *
     * @mbg.generated
     */
    private String previousName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.phone1
     *
     * @mbg.generated
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.phone2
     *
     * @mbg.generated
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.customer_manager_id
     *
     * @mbg.generated
     */
    private Integer customerManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.manager_phone
     *
     * @mbg.generated
     */
    private String managerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.data_status
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.business_manager_id
     *
     * @mbg.generated
     */
    private Integer businessManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_history_info.operator_type
     *
     * @mbg.generated
     */
    private String operatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_history_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.id
     *
     * @return the value of customer_history_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.id
     *
     * @param id the value for customer_history_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.name
     *
     * @return the value of customer_history_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.name
     *
     * @param name the value for customer_history_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.previous_name
     *
     * @return the value of customer_history_info.previous_name
     *
     * @mbg.generated
     */
    public String getPreviousName() {
        return previousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.previous_name
     *
     * @param previousName the value for customer_history_info.previous_name
     *
     * @mbg.generated
     */
    public void setPreviousName(String previousName) {
        this.previousName = previousName == null ? null : previousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.address
     *
     * @return the value of customer_history_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.address
     *
     * @param address the value for customer_history_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.area_id
     *
     * @return the value of customer_history_info.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.area_id
     *
     * @param areaId the value for customer_history_info.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.contact_person
     *
     * @return the value of customer_history_info.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.contact_person
     *
     * @param contactPerson the value for customer_history_info.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.phone1
     *
     * @return the value of customer_history_info.phone1
     *
     * @mbg.generated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.phone1
     *
     * @param phone1 the value for customer_history_info.phone1
     *
     * @mbg.generated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.phone2
     *
     * @return the value of customer_history_info.phone2
     *
     * @mbg.generated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.phone2
     *
     * @param phone2 the value for customer_history_info.phone2
     *
     * @mbg.generated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.customer_manager_id
     *
     * @return the value of customer_history_info.customer_manager_id
     *
     * @mbg.generated
     */
    public Integer getCustomerManagerId() {
        return customerManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.customer_manager_id
     *
     * @param customerManagerId the value for customer_history_info.customer_manager_id
     *
     * @mbg.generated
     */
    public void setCustomerManagerId(Integer customerManagerId) {
        this.customerManagerId = customerManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.manager_phone
     *
     * @return the value of customer_history_info.manager_phone
     *
     * @mbg.generated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.manager_phone
     *
     * @param managerPhone the value for customer_history_info.manager_phone
     *
     * @mbg.generated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.status
     *
     * @return the value of customer_history_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.status
     *
     * @param status the value for customer_history_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.create_time
     *
     * @return the value of customer_history_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.create_time
     *
     * @param createTime the value for customer_history_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.data_status
     *
     * @return the value of customer_history_info.data_status
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.data_status
     *
     * @param dataStatus the value for customer_history_info.data_status
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.operator_id
     *
     * @return the value of customer_history_info.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.operator_id
     *
     * @param operatorId the value for customer_history_info.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.customer_id
     *
     * @return the value of customer_history_info.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.customer_id
     *
     * @param customerId the value for customer_history_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.business_manager_id
     *
     * @return the value of customer_history_info.business_manager_id
     *
     * @mbg.generated
     */
    public Integer getBusinessManagerId() {
        return businessManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.business_manager_id
     *
     * @param businessManagerId the value for customer_history_info.business_manager_id
     *
     * @mbg.generated
     */
    public void setBusinessManagerId(Integer businessManagerId) {
        this.businessManagerId = businessManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_history_info.operator_type
     *
     * @return the value of customer_history_info.operator_type
     *
     * @mbg.generated
     */
    public String getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_history_info.operator_type
     *
     * @param operatorType the value for customer_history_info.operator_type
     *
     * @mbg.generated
     */
    public void setOperatorType(String operatorType) {
        this.operatorType = operatorType == null ? null : operatorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_history_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", previousName=").append(previousName);
        sb.append(", address=").append(address);
        sb.append(", areaId=").append(areaId);
        sb.append(", contactPerson=").append(contactPerson);
        sb.append(", phone1=").append(phone1);
        sb.append(", phone2=").append(phone2);
        sb.append(", customerManagerId=").append(customerManagerId);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", customerId=").append(customerId);
        sb.append(", businessManagerId=").append(businessManagerId);
        sb.append(", operatorType=").append(operatorType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}