package com.springboot.crm.entity;

import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.previous_name
     *
     * @mbg.generated
     */
    private String previousName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone1
     *
     * @mbg.generated
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone2
     *
     * @mbg.generated
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_manager
     *
     * @mbg.generated
     */
    private String customerManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_manager_id
     *
     * @mbg.generated
     */
    private Integer customerManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.manager_phone
     *
     * @mbg.generated
     */
    private String managerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.business_manager
     *
     * @mbg.generated
     */
    private String businessManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.business_manager_id
     *
     * @mbg.generated
     */
    private Integer businessManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.data_status
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.edit_time
     *
     * @mbg.generated
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.edit_operator_id
     *
     * @mbg.generated
     */
    private Integer editOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.previous_name
     *
     * @return the value of customer.previous_name
     *
     * @mbg.generated
     */
    public String getPreviousName() {
        return previousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.previous_name
     *
     * @param previousName the value for customer.previous_name
     *
     * @mbg.generated
     */
    public void setPreviousName(String previousName) {
        this.previousName = previousName == null ? null : previousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.area
     *
     * @return the value of customer.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.area
     *
     * @param area the value for customer.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.area_id
     *
     * @return the value of customer.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.area_id
     *
     * @param areaId the value for customer.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact_person
     *
     * @return the value of customer.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact_person
     *
     * @param contactPerson the value for customer.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone1
     *
     * @return the value of customer.phone1
     *
     * @mbg.generated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone1
     *
     * @param phone1 the value for customer.phone1
     *
     * @mbg.generated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone2
     *
     * @return the value of customer.phone2
     *
     * @mbg.generated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone2
     *
     * @param phone2 the value for customer.phone2
     *
     * @mbg.generated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_manager
     *
     * @return the value of customer.customer_manager
     *
     * @mbg.generated
     */
    public String getCustomerManager() {
        return customerManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_manager
     *
     * @param customerManager the value for customer.customer_manager
     *
     * @mbg.generated
     */
    public void setCustomerManager(String customerManager) {
        this.customerManager = customerManager == null ? null : customerManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_manager_id
     *
     * @return the value of customer.customer_manager_id
     *
     * @mbg.generated
     */
    public Integer getCustomerManagerId() {
        return customerManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_manager_id
     *
     * @param customerManagerId the value for customer.customer_manager_id
     *
     * @mbg.generated
     */
    public void setCustomerManagerId(Integer customerManagerId) {
        this.customerManagerId = customerManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.manager_phone
     *
     * @return the value of customer.manager_phone
     *
     * @mbg.generated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.manager_phone
     *
     * @param managerPhone the value for customer.manager_phone
     *
     * @mbg.generated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.business_manager
     *
     * @return the value of customer.business_manager
     *
     * @mbg.generated
     */
    public String getBusinessManager() {
        return businessManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.business_manager
     *
     * @param businessManager the value for customer.business_manager
     *
     * @mbg.generated
     */
    public void setBusinessManager(String businessManager) {
        this.businessManager = businessManager == null ? null : businessManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.business_manager_id
     *
     * @return the value of customer.business_manager_id
     *
     * @mbg.generated
     */
    public Integer getBusinessManagerId() {
        return businessManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.business_manager_id
     *
     * @param businessManagerId the value for customer.business_manager_id
     *
     * @mbg.generated
     */
    public void setBusinessManagerId(Integer businessManagerId) {
        this.businessManagerId = businessManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_time
     *
     * @return the value of customer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_time
     *
     * @param createTime the value for customer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.data_status
     *
     * @return the value of customer.data_status
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.data_status
     *
     * @param dataStatus the value for customer.data_status
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.operator_id
     *
     * @return the value of customer.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.operator_id
     *
     * @param operatorId the value for customer.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.edit_time
     *
     * @return the value of customer.edit_time
     *
     * @mbg.generated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.edit_time
     *
     * @param editTime the value for customer.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.edit_operator_id
     *
     * @return the value of customer.edit_operator_id
     *
     * @mbg.generated
     */
    public Integer getEditOperatorId() {
        return editOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.edit_operator_id
     *
     * @param editOperatorId the value for customer.edit_operator_id
     *
     * @mbg.generated
     */
    public void setEditOperatorId(Integer editOperatorId) {
        this.editOperatorId = editOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", previousName=").append(previousName);
        sb.append(", address=").append(address);
        sb.append(", area=").append(area);
        sb.append(", areaId=").append(areaId);
        sb.append(", contactPerson=").append(contactPerson);
        sb.append(", phone1=").append(phone1);
        sb.append(", phone2=").append(phone2);
        sb.append(", customerManager=").append(customerManager);
        sb.append(", customerManagerId=").append(customerManagerId);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", businessManager=").append(businessManager);
        sb.append(", businessManagerId=").append(businessManagerId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", editTime=").append(editTime);
        sb.append(", editOperatorId=").append(editOperatorId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    private String operator;

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }
}