package com.springboot.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EditGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public EditGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("equipment_id is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("equipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(Integer value) {
            addCriterion("equipment_id =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(Integer value) {
            addCriterion("equipment_id <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(Integer value) {
            addCriterion("equipment_id >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("equipment_id >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(Integer value) {
            addCriterion("equipment_id <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("equipment_id <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<Integer> values) {
            addCriterion("equipment_id in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<Integer> values) {
            addCriterion("equipment_id not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(Integer value1, Integer value2) {
            addCriterion("equipment_id between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("equipment_id not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("`number` is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("`number` is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("`number` =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("`number` <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("`number` >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("`number` >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("`number` <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("`number` <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("`number` like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("`number` not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("`number` in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("`number` not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("`number` between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("`number` not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIsNull() {
            addCriterion("purchase_time is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIsNotNull() {
            addCriterion("purchase_time is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeEqualTo(Date value) {
            addCriterion("purchase_time =", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotEqualTo(Date value) {
            addCriterion("purchase_time <>", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeGreaterThan(Date value) {
            addCriterion("purchase_time >", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("purchase_time >=", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeLessThan(Date value) {
            addCriterion("purchase_time <", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeLessThanOrEqualTo(Date value) {
            addCriterion("purchase_time <=", value, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeIn(List<Date> values) {
            addCriterion("purchase_time in", values, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotIn(List<Date> values) {
            addCriterion("purchase_time not in", values, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeBetween(Date value1, Date value2) {
            addCriterion("purchase_time between", value1, value2, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andPurchaseTimeNotBetween(Date value1, Date value2) {
            addCriterion("purchase_time not between", value1, value2, "purchaseTime");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdIsNull() {
            addCriterion("using_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdIsNotNull() {
            addCriterion("using_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdEqualTo(Integer value) {
            addCriterion("using_customer_id =", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdNotEqualTo(Integer value) {
            addCriterion("using_customer_id <>", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdGreaterThan(Integer value) {
            addCriterion("using_customer_id >", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("using_customer_id >=", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdLessThan(Integer value) {
            addCriterion("using_customer_id <", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("using_customer_id <=", value, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdIn(List<Integer> values) {
            addCriterion("using_customer_id in", values, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdNotIn(List<Integer> values) {
            addCriterion("using_customer_id not in", values, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("using_customer_id between", value1, value2, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andUsingCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("using_customer_id not between", value1, value2, "usingCustomerId");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeIsNull() {
            addCriterion("in_storage_time is null");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeIsNotNull() {
            addCriterion("in_storage_time is not null");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeEqualTo(Date value) {
            addCriterion("in_storage_time =", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeNotEqualTo(Date value) {
            addCriterion("in_storage_time <>", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeGreaterThan(Date value) {
            addCriterion("in_storage_time >", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("in_storage_time >=", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeLessThan(Date value) {
            addCriterion("in_storage_time <", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeLessThanOrEqualTo(Date value) {
            addCriterion("in_storage_time <=", value, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeIn(List<Date> values) {
            addCriterion("in_storage_time in", values, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeNotIn(List<Date> values) {
            addCriterion("in_storage_time not in", values, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeBetween(Date value1, Date value2) {
            addCriterion("in_storage_time between", value1, value2, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStorageTimeNotBetween(Date value1, Date value2) {
            addCriterion("in_storage_time not between", value1, value2, "inStorageTime");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdIsNull() {
            addCriterion("in_storage_people_id is null");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdIsNotNull() {
            addCriterion("in_storage_people_id is not null");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdEqualTo(Integer value) {
            addCriterion("in_storage_people_id =", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdNotEqualTo(Integer value) {
            addCriterion("in_storage_people_id <>", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdGreaterThan(Integer value) {
            addCriterion("in_storage_people_id >", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_storage_people_id >=", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdLessThan(Integer value) {
            addCriterion("in_storage_people_id <", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdLessThanOrEqualTo(Integer value) {
            addCriterion("in_storage_people_id <=", value, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdIn(List<Integer> values) {
            addCriterion("in_storage_people_id in", values, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdNotIn(List<Integer> values) {
            addCriterion("in_storage_people_id not in", values, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdBetween(Integer value1, Integer value2) {
            addCriterion("in_storage_people_id between", value1, value2, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andInStoragePeopleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("in_storage_people_id not between", value1, value2, "inStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeIsNull() {
            addCriterion("out_storage_time is null");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeIsNotNull() {
            addCriterion("out_storage_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeEqualTo(Date value) {
            addCriterion("out_storage_time =", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeNotEqualTo(Date value) {
            addCriterion("out_storage_time <>", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeGreaterThan(Date value) {
            addCriterion("out_storage_time >", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("out_storage_time >=", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeLessThan(Date value) {
            addCriterion("out_storage_time <", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeLessThanOrEqualTo(Date value) {
            addCriterion("out_storage_time <=", value, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeIn(List<Date> values) {
            addCriterion("out_storage_time in", values, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeNotIn(List<Date> values) {
            addCriterion("out_storage_time not in", values, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeBetween(Date value1, Date value2) {
            addCriterion("out_storage_time between", value1, value2, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStorageTimeNotBetween(Date value1, Date value2) {
            addCriterion("out_storage_time not between", value1, value2, "outStorageTime");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdIsNull() {
            addCriterion("out_storage_people_id is null");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdIsNotNull() {
            addCriterion("out_storage_people_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdEqualTo(Integer value) {
            addCriterion("out_storage_people_id =", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdNotEqualTo(Integer value) {
            addCriterion("out_storage_people_id <>", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdGreaterThan(Integer value) {
            addCriterion("out_storage_people_id >", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("out_storage_people_id >=", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdLessThan(Integer value) {
            addCriterion("out_storage_people_id <", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdLessThanOrEqualTo(Integer value) {
            addCriterion("out_storage_people_id <=", value, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdIn(List<Integer> values) {
            addCriterion("out_storage_people_id in", values, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdNotIn(List<Integer> values) {
            addCriterion("out_storage_people_id not in", values, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdBetween(Integer value1, Integer value2) {
            addCriterion("out_storage_people_id between", value1, value2, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andOutStoragePeopleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("out_storage_people_id not between", value1, value2, "outStoragePeopleId");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIsNull() {
            addCriterion("device_code is null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIsNotNull() {
            addCriterion("device_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeEqualTo(String value) {
            addCriterion("device_code =", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeNotEqualTo(String value) {
            addCriterion("device_code <>", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeGreaterThan(String value) {
            addCriterion("device_code >", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("device_code >=", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeLessThan(String value) {
            addCriterion("device_code <", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeLessThanOrEqualTo(String value) {
            addCriterion("device_code <=", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeLike(String value) {
            addCriterion("device_code like", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeNotLike(String value) {
            addCriterion("device_code not like", value, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeIn(List<String> values) {
            addCriterion("device_code in", values, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeNotIn(List<String> values) {
            addCriterion("device_code not in", values, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeBetween(String value1, String value2) {
            addCriterion("device_code between", value1, value2, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andDeviceCodeNotBetween(String value1, String value2) {
            addCriterion("device_code not between", value1, value2, "deviceCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeIsNull() {
            addCriterion("hardware_code is null");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeIsNotNull() {
            addCriterion("hardware_code is not null");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeEqualTo(String value) {
            addCriterion("hardware_code =", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeNotEqualTo(String value) {
            addCriterion("hardware_code <>", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeGreaterThan(String value) {
            addCriterion("hardware_code >", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeGreaterThanOrEqualTo(String value) {
            addCriterion("hardware_code >=", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeLessThan(String value) {
            addCriterion("hardware_code <", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeLessThanOrEqualTo(String value) {
            addCriterion("hardware_code <=", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeLike(String value) {
            addCriterion("hardware_code like", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeNotLike(String value) {
            addCriterion("hardware_code not like", value, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeIn(List<String> values) {
            addCriterion("hardware_code in", values, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeNotIn(List<String> values) {
            addCriterion("hardware_code not in", values, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeBetween(String value1, String value2) {
            addCriterion("hardware_code between", value1, value2, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andHardwareCodeNotBetween(String value1, String value2) {
            addCriterion("hardware_code not between", value1, value2, "hardwareCode");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdIsNull() {
            addCriterion("storage_area_id is null");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdIsNotNull() {
            addCriterion("storage_area_id is not null");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdEqualTo(Integer value) {
            addCriterion("storage_area_id =", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdNotEqualTo(Integer value) {
            addCriterion("storage_area_id <>", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdGreaterThan(Integer value) {
            addCriterion("storage_area_id >", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("storage_area_id >=", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdLessThan(Integer value) {
            addCriterion("storage_area_id <", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdLessThanOrEqualTo(Integer value) {
            addCriterion("storage_area_id <=", value, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdIn(List<Integer> values) {
            addCriterion("storage_area_id in", values, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdNotIn(List<Integer> values) {
            addCriterion("storage_area_id not in", values, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdBetween(Integer value1, Integer value2) {
            addCriterion("storage_area_id between", value1, value2, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andStorageAreaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("storage_area_id not between", value1, value2, "storageAreaId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Integer value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Integer value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Integer value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Integer value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Integer> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Integer> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdIsNull() {
            addCriterion("edit_operater_id is null");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdIsNotNull() {
            addCriterion("edit_operater_id is not null");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdEqualTo(Integer value) {
            addCriterion("edit_operater_id =", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdNotEqualTo(Integer value) {
            addCriterion("edit_operater_id <>", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdGreaterThan(Integer value) {
            addCriterion("edit_operater_id >", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("edit_operater_id >=", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdLessThan(Integer value) {
            addCriterion("edit_operater_id <", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdLessThanOrEqualTo(Integer value) {
            addCriterion("edit_operater_id <=", value, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdIn(List<Integer> values) {
            addCriterion("edit_operater_id in", values, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdNotIn(List<Integer> values) {
            addCriterion("edit_operater_id not in", values, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdBetween(Integer value1, Integer value2) {
            addCriterion("edit_operater_id between", value1, value2, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andEditOperaterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("edit_operater_id not between", value1, value2, "editOperaterId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edit_goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edit_goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}