package com.springboot.crm.entity;

import com.springboot.crm.config.SpringContext;
import com.springboot.crm.dao.EmployeeTypeMapper;
import com.springboot.crm.dao.TypeMapper;
import com.springboot.crm.service.TypeService;
import org.springframework.context.ApplicationContext;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.*;

public class Employee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hire_date
     *
     * @mbg.generated
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.change_password_cycle
     *
     * @mbg.generated
     */
    private Integer changePasswordCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.operatorId
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.edit_time
     *
     * @mbg.generated
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password_change_time
     *
     * @mbg.generated
     */
    private LocalDate passwordChangeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    //员工角色
    private Set<Type> roles = new HashSet<>();

    private List<Integer> manageArea = new ArrayList<>();

    public List<Integer> getManageArea() {
        return manageArea;
    }

    public void setManageArea(List<Integer> manageArea) {
        this.manageArea = manageArea;
    }

    public Set<Type> getRolesById() {
        ApplicationContext context = SpringContext.getApplicationContext();
        EmployeeTypeMapper employeeTypeMapper = context.getBean(EmployeeTypeMapper.class);
        EmployeeTypeExample example = new EmployeeTypeExample();
        EmployeeTypeExample.Criteria criteria = example.createCriteria();
        //找到员工角色表中 employee id为该id的数据
        criteria.andEmployeeIdEqualTo(id);
        List<EmployeeType> list = employeeTypeMapper.selectByExample(example);

        for (EmployeeType type : list) {
            //返回每一行数据的角色id
            int tid = type.getTypeId();
            TypeMapper typeMapper = context.getBean(TypeMapper.class);
            //根据id找到相对应的角色
            Type role = typeMapper.selectByPrimaryKey(tid);
            roles.add(role);
        }
        return roles;
    }

    public void setRoles(List<Integer> roles) {
        ApplicationContext context = SpringContext.getApplicationContext();
        Set<Type> types = new HashSet<>();
        for (int i=0; i<roles.size(); i++) {
            int roleId = roles.get(i);
            TypeService typeService = context.getBean(TypeService.class);
            Type type = typeService.getTypeById(roleId);
            types.add(type);
        }
        this.roles = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.account
     *
     * @return the value of employee.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.account
     *
     * @param account the value for employee.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hire_date
     *
     * @return the value of employee.hire_date
     *
     * @mbg.generated
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hire_date
     *
     * @param hireDate the value for employee.hire_date
     *
     * @mbg.generated
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department
     *
     * @return the value of employee.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department
     *
     * @param department the value for employee.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.province
     *
     * @return the value of employee.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.province
     *
     * @param province the value for employee.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.change_password_cycle
     *
     * @return the value of employee.change_password_cycle
     *
     * @mbg.generated
     */
    public Integer getChangePasswordCycle() {
        return changePasswordCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.change_password_cycle
     *
     * @param changePasswordCycle the value for employee.change_password_cycle
     *
     * @mbg.generated
     */
    public void setChangePasswordCycle(Integer changePasswordCycle) {
        this.changePasswordCycle = changePasswordCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.operatorId
     *
     * @return the value of employee.operatorId
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.operatorId
     *
     * @param operatorid the value for employee.operatorId
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.edit_time
     *
     * @return the value of employee.edit_time
     *
     * @mbg.generated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.edit_time
     *
     * @param editTime the value for employee.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password_change_time
     *
     * @return the value of employee.password_change_time
     *
     * @mbg.generated
     */
    public LocalDate getPasswordChangeTime() {
        return passwordChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password_change_time
     *
     * @param passwordChangeTime the value for employee.password_change_time
     *
     * @mbg.generated
     */
    public void setPasswordChangeTime(LocalDate passwordChangeTime) {
        this.passwordChangeTime = passwordChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", account=").append(account);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", hireDate=").append(hireDate);
        sb.append(", department=").append(department);
        sb.append(", password=").append(password);
        sb.append(", province=").append(province);
        sb.append(", changePasswordCycle=").append(changePasswordCycle);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", editTime=").append(editTime);
        sb.append(", passwordChangeTime=").append(passwordChangeTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public Set<Type> getRoles() {
        return roles;
    }
}