package com.springboot.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EquipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public EquipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andModelNumberIsNull() {
            addCriterion("model_number is null");
            return (Criteria) this;
        }

        public Criteria andModelNumberIsNotNull() {
            addCriterion("model_number is not null");
            return (Criteria) this;
        }

        public Criteria andModelNumberEqualTo(String value) {
            addCriterion("model_number =", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotEqualTo(String value) {
            addCriterion("model_number <>", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberGreaterThan(String value) {
            addCriterion("model_number >", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberGreaterThanOrEqualTo(String value) {
            addCriterion("model_number >=", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLessThan(String value) {
            addCriterion("model_number <", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLessThanOrEqualTo(String value) {
            addCriterion("model_number <=", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLike(String value) {
            addCriterion("model_number like", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotLike(String value) {
            addCriterion("model_number not like", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberIn(List<String> values) {
            addCriterion("model_number in", values, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotIn(List<String> values) {
            addCriterion("model_number not in", values, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberBetween(String value1, String value2) {
            addCriterion("model_number between", value1, value2, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotBetween(String value1, String value2) {
            addCriterion("model_number not between", value1, value2, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("manufacturer is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("manufacturer is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("manufacturer =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("manufacturer <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("manufacturer >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("manufacturer <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("manufacturer <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("manufacturer like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("manufacturer not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("manufacturer in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("manufacturer not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("manufacturer between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("manufacturer not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNull() {
            addCriterion("`attribute` is null");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNotNull() {
            addCriterion("`attribute` is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeEqualTo(String value) {
            addCriterion("`attribute` =", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotEqualTo(String value) {
            addCriterion("`attribute` <>", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThan(String value) {
            addCriterion("`attribute` >", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThanOrEqualTo(String value) {
            addCriterion("`attribute` >=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThan(String value) {
            addCriterion("`attribute` <", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThanOrEqualTo(String value) {
            addCriterion("`attribute` <=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLike(String value) {
            addCriterion("`attribute` like", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotLike(String value) {
            addCriterion("`attribute` not like", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeIn(List<String> values) {
            addCriterion("`attribute` in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotIn(List<String> values) {
            addCriterion("`attribute` not in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeBetween(String value1, String value2) {
            addCriterion("`attribute` between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotBetween(String value1, String value2) {
            addCriterion("`attribute` not between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Integer value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Integer value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Integer value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Integer value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Integer value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Integer> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Integer> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Integer value1, Integer value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andBandWidthIsNull() {
            addCriterion("band_width is null");
            return (Criteria) this;
        }

        public Criteria andBandWidthIsNotNull() {
            addCriterion("band_width is not null");
            return (Criteria) this;
        }

        public Criteria andBandWidthEqualTo(String value) {
            addCriterion("band_width =", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotEqualTo(String value) {
            addCriterion("band_width <>", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthGreaterThan(String value) {
            addCriterion("band_width >", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthGreaterThanOrEqualTo(String value) {
            addCriterion("band_width >=", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLessThan(String value) {
            addCriterion("band_width <", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLessThanOrEqualTo(String value) {
            addCriterion("band_width <=", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthLike(String value) {
            addCriterion("band_width like", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotLike(String value) {
            addCriterion("band_width not like", value, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthIn(List<String> values) {
            addCriterion("band_width in", values, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotIn(List<String> values) {
            addCriterion("band_width not in", values, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthBetween(String value1, String value2) {
            addCriterion("band_width between", value1, value2, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andBandWidthNotBetween(String value1, String value2) {
            addCriterion("band_width not between", value1, value2, "bandWidth");
            return (Criteria) this;
        }

        public Criteria andPort1IsNull() {
            addCriterion("port1 is null");
            return (Criteria) this;
        }

        public Criteria andPort1IsNotNull() {
            addCriterion("port1 is not null");
            return (Criteria) this;
        }

        public Criteria andPort1EqualTo(Integer value) {
            addCriterion("port1 =", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1NotEqualTo(Integer value) {
            addCriterion("port1 <>", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1GreaterThan(Integer value) {
            addCriterion("port1 >", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1GreaterThanOrEqualTo(Integer value) {
            addCriterion("port1 >=", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1LessThan(Integer value) {
            addCriterion("port1 <", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1LessThanOrEqualTo(Integer value) {
            addCriterion("port1 <=", value, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1In(List<Integer> values) {
            addCriterion("port1 in", values, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1NotIn(List<Integer> values) {
            addCriterion("port1 not in", values, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1Between(Integer value1, Integer value2) {
            addCriterion("port1 between", value1, value2, "port1");
            return (Criteria) this;
        }

        public Criteria andPort1NotBetween(Integer value1, Integer value2) {
            addCriterion("port1 not between", value1, value2, "port1");
            return (Criteria) this;
        }

        public Criteria andPort2IsNull() {
            addCriterion("port2 is null");
            return (Criteria) this;
        }

        public Criteria andPort2IsNotNull() {
            addCriterion("port2 is not null");
            return (Criteria) this;
        }

        public Criteria andPort2EqualTo(Integer value) {
            addCriterion("port2 =", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2NotEqualTo(Integer value) {
            addCriterion("port2 <>", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2GreaterThan(Integer value) {
            addCriterion("port2 >", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2GreaterThanOrEqualTo(Integer value) {
            addCriterion("port2 >=", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2LessThan(Integer value) {
            addCriterion("port2 <", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2LessThanOrEqualTo(Integer value) {
            addCriterion("port2 <=", value, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2In(List<Integer> values) {
            addCriterion("port2 in", values, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2NotIn(List<Integer> values) {
            addCriterion("port2 not in", values, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2Between(Integer value1, Integer value2) {
            addCriterion("port2 between", value1, value2, "port2");
            return (Criteria) this;
        }

        public Criteria andPort2NotBetween(Integer value1, Integer value2) {
            addCriterion("port2 not between", value1, value2, "port2");
            return (Criteria) this;
        }

        public Criteria andPort3IsNull() {
            addCriterion("port3 is null");
            return (Criteria) this;
        }

        public Criteria andPort3IsNotNull() {
            addCriterion("port3 is not null");
            return (Criteria) this;
        }

        public Criteria andPort3EqualTo(Integer value) {
            addCriterion("port3 =", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3NotEqualTo(Integer value) {
            addCriterion("port3 <>", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3GreaterThan(Integer value) {
            addCriterion("port3 >", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3GreaterThanOrEqualTo(Integer value) {
            addCriterion("port3 >=", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3LessThan(Integer value) {
            addCriterion("port3 <", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3LessThanOrEqualTo(Integer value) {
            addCriterion("port3 <=", value, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3In(List<Integer> values) {
            addCriterion("port3 in", values, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3NotIn(List<Integer> values) {
            addCriterion("port3 not in", values, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3Between(Integer value1, Integer value2) {
            addCriterion("port3 between", value1, value2, "port3");
            return (Criteria) this;
        }

        public Criteria andPort3NotBetween(Integer value1, Integer value2) {
            addCriterion("port3 not between", value1, value2, "port3");
            return (Criteria) this;
        }

        public Criteria andPort4IsNull() {
            addCriterion("port4 is null");
            return (Criteria) this;
        }

        public Criteria andPort4IsNotNull() {
            addCriterion("port4 is not null");
            return (Criteria) this;
        }

        public Criteria andPort4EqualTo(Integer value) {
            addCriterion("port4 =", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4NotEqualTo(Integer value) {
            addCriterion("port4 <>", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4GreaterThan(Integer value) {
            addCriterion("port4 >", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4GreaterThanOrEqualTo(Integer value) {
            addCriterion("port4 >=", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4LessThan(Integer value) {
            addCriterion("port4 <", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4LessThanOrEqualTo(Integer value) {
            addCriterion("port4 <=", value, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4In(List<Integer> values) {
            addCriterion("port4 in", values, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4NotIn(List<Integer> values) {
            addCriterion("port4 not in", values, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4Between(Integer value1, Integer value2) {
            addCriterion("port4 between", value1, value2, "port4");
            return (Criteria) this;
        }

        public Criteria andPort4NotBetween(Integer value1, Integer value2) {
            addCriterion("port4 not between", value1, value2, "port4");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1IsNull() {
            addCriterion("handling_capacity1 is null");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1IsNotNull() {
            addCriterion("handling_capacity1 is not null");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1EqualTo(String value) {
            addCriterion("handling_capacity1 =", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1NotEqualTo(String value) {
            addCriterion("handling_capacity1 <>", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1GreaterThan(String value) {
            addCriterion("handling_capacity1 >", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1GreaterThanOrEqualTo(String value) {
            addCriterion("handling_capacity1 >=", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1LessThan(String value) {
            addCriterion("handling_capacity1 <", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1LessThanOrEqualTo(String value) {
            addCriterion("handling_capacity1 <=", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1Like(String value) {
            addCriterion("handling_capacity1 like", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1NotLike(String value) {
            addCriterion("handling_capacity1 not like", value, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1In(List<String> values) {
            addCriterion("handling_capacity1 in", values, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1NotIn(List<String> values) {
            addCriterion("handling_capacity1 not in", values, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1Between(String value1, String value2) {
            addCriterion("handling_capacity1 between", value1, value2, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity1NotBetween(String value1, String value2) {
            addCriterion("handling_capacity1 not between", value1, value2, "handlingCapacity1");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2IsNull() {
            addCriterion("handling_capacity2 is null");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2IsNotNull() {
            addCriterion("handling_capacity2 is not null");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2EqualTo(String value) {
            addCriterion("handling_capacity2 =", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2NotEqualTo(String value) {
            addCriterion("handling_capacity2 <>", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2GreaterThan(String value) {
            addCriterion("handling_capacity2 >", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2GreaterThanOrEqualTo(String value) {
            addCriterion("handling_capacity2 >=", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2LessThan(String value) {
            addCriterion("handling_capacity2 <", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2LessThanOrEqualTo(String value) {
            addCriterion("handling_capacity2 <=", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2Like(String value) {
            addCriterion("handling_capacity2 like", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2NotLike(String value) {
            addCriterion("handling_capacity2 not like", value, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2In(List<String> values) {
            addCriterion("handling_capacity2 in", values, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2NotIn(List<String> values) {
            addCriterion("handling_capacity2 not in", values, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2Between(String value1, String value2) {
            addCriterion("handling_capacity2 between", value1, value2, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andHandlingCapacity2NotBetween(String value1, String value2) {
            addCriterion("handling_capacity2 not between", value1, value2, "handlingCapacity2");
            return (Criteria) this;
        }

        public Criteria andFunction1IsNull() {
            addCriterion("function1 is null");
            return (Criteria) this;
        }

        public Criteria andFunction1IsNotNull() {
            addCriterion("function1 is not null");
            return (Criteria) this;
        }

        public Criteria andFunction1EqualTo(String value) {
            addCriterion("function1 =", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1NotEqualTo(String value) {
            addCriterion("function1 <>", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1GreaterThan(String value) {
            addCriterion("function1 >", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1GreaterThanOrEqualTo(String value) {
            addCriterion("function1 >=", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1LessThan(String value) {
            addCriterion("function1 <", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1LessThanOrEqualTo(String value) {
            addCriterion("function1 <=", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1Like(String value) {
            addCriterion("function1 like", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1NotLike(String value) {
            addCriterion("function1 not like", value, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1In(List<String> values) {
            addCriterion("function1 in", values, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1NotIn(List<String> values) {
            addCriterion("function1 not in", values, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1Between(String value1, String value2) {
            addCriterion("function1 between", value1, value2, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction1NotBetween(String value1, String value2) {
            addCriterion("function1 not between", value1, value2, "function1");
            return (Criteria) this;
        }

        public Criteria andFunction2IsNull() {
            addCriterion("function2 is null");
            return (Criteria) this;
        }

        public Criteria andFunction2IsNotNull() {
            addCriterion("function2 is not null");
            return (Criteria) this;
        }

        public Criteria andFunction2EqualTo(String value) {
            addCriterion("function2 =", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2NotEqualTo(String value) {
            addCriterion("function2 <>", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2GreaterThan(String value) {
            addCriterion("function2 >", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2GreaterThanOrEqualTo(String value) {
            addCriterion("function2 >=", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2LessThan(String value) {
            addCriterion("function2 <", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2LessThanOrEqualTo(String value) {
            addCriterion("function2 <=", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2Like(String value) {
            addCriterion("function2 like", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2NotLike(String value) {
            addCriterion("function2 not like", value, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2In(List<String> values) {
            addCriterion("function2 in", values, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2NotIn(List<String> values) {
            addCriterion("function2 not in", values, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2Between(String value1, String value2) {
            addCriterion("function2 between", value1, value2, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction2NotBetween(String value1, String value2) {
            addCriterion("function2 not between", value1, value2, "function2");
            return (Criteria) this;
        }

        public Criteria andFunction3IsNull() {
            addCriterion("function3 is null");
            return (Criteria) this;
        }

        public Criteria andFunction3IsNotNull() {
            addCriterion("function3 is not null");
            return (Criteria) this;
        }

        public Criteria andFunction3EqualTo(String value) {
            addCriterion("function3 =", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3NotEqualTo(String value) {
            addCriterion("function3 <>", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3GreaterThan(String value) {
            addCriterion("function3 >", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3GreaterThanOrEqualTo(String value) {
            addCriterion("function3 >=", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3LessThan(String value) {
            addCriterion("function3 <", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3LessThanOrEqualTo(String value) {
            addCriterion("function3 <=", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3Like(String value) {
            addCriterion("function3 like", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3NotLike(String value) {
            addCriterion("function3 not like", value, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3In(List<String> values) {
            addCriterion("function3 in", values, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3NotIn(List<String> values) {
            addCriterion("function3 not in", values, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3Between(String value1, String value2) {
            addCriterion("function3 between", value1, value2, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction3NotBetween(String value1, String value2) {
            addCriterion("function3 not between", value1, value2, "function3");
            return (Criteria) this;
        }

        public Criteria andFunction4IsNull() {
            addCriterion("function4 is null");
            return (Criteria) this;
        }

        public Criteria andFunction4IsNotNull() {
            addCriterion("function4 is not null");
            return (Criteria) this;
        }

        public Criteria andFunction4EqualTo(String value) {
            addCriterion("function4 =", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4NotEqualTo(String value) {
            addCriterion("function4 <>", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4GreaterThan(String value) {
            addCriterion("function4 >", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4GreaterThanOrEqualTo(String value) {
            addCriterion("function4 >=", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4LessThan(String value) {
            addCriterion("function4 <", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4LessThanOrEqualTo(String value) {
            addCriterion("function4 <=", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4Like(String value) {
            addCriterion("function4 like", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4NotLike(String value) {
            addCriterion("function4 not like", value, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4In(List<String> values) {
            addCriterion("function4 in", values, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4NotIn(List<String> values) {
            addCriterion("function4 not in", values, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4Between(String value1, String value2) {
            addCriterion("function4 between", value1, value2, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction4NotBetween(String value1, String value2) {
            addCriterion("function4 not between", value1, value2, "function4");
            return (Criteria) this;
        }

        public Criteria andFunction5IsNull() {
            addCriterion("function5 is null");
            return (Criteria) this;
        }

        public Criteria andFunction5IsNotNull() {
            addCriterion("function5 is not null");
            return (Criteria) this;
        }

        public Criteria andFunction5EqualTo(String value) {
            addCriterion("function5 =", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5NotEqualTo(String value) {
            addCriterion("function5 <>", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5GreaterThan(String value) {
            addCriterion("function5 >", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5GreaterThanOrEqualTo(String value) {
            addCriterion("function5 >=", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5LessThan(String value) {
            addCriterion("function5 <", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5LessThanOrEqualTo(String value) {
            addCriterion("function5 <=", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5Like(String value) {
            addCriterion("function5 like", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5NotLike(String value) {
            addCriterion("function5 not like", value, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5In(List<String> values) {
            addCriterion("function5 in", values, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5NotIn(List<String> values) {
            addCriterion("function5 not in", values, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5Between(String value1, String value2) {
            addCriterion("function5 between", value1, value2, "function5");
            return (Criteria) this;
        }

        public Criteria andFunction5NotBetween(String value1, String value2) {
            addCriterion("function5 not between", value1, value2, "function5");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Integer value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Integer value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Integer value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Integer value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Integer> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Integer> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}