package com.springboot.crm.entity;

import java.io.Serializable;
import java.util.Date;

public class Equipment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.model_number
     *
     * @mbg.generated
     */
    private String modelNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.manufacturer
     *
     * @mbg.generated
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.attribute
     *
     * @mbg.generated
     */
    private String attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.band_width
     *
     * @mbg.generated
     */
    private String bandWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.port1
     *
     * @mbg.generated
     */
    private Integer port1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.port2
     *
     * @mbg.generated
     */
    private Integer port2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.port3
     *
     * @mbg.generated
     */
    private Integer port3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.port4
     *
     * @mbg.generated
     */
    private Integer port4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.handling_capacity1
     *
     * @mbg.generated
     */
    private String handlingCapacity1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.handling_capacity2
     *
     * @mbg.generated
     */
    private String handlingCapacity2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.function1
     *
     * @mbg.generated
     */
    private String function1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.function2
     *
     * @mbg.generated
     */
    private String function2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.function3
     *
     * @mbg.generated
     */
    private String function3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.function4
     *
     * @mbg.generated
     */
    private String function4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.function5
     *
     * @mbg.generated
     */
    private String function5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.edit_time
     *
     * @mbg.generated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.id
     *
     * @return the value of equipment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.id
     *
     * @param id the value for equipment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.type
     *
     * @return the value of equipment.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.type
     *
     * @param type the value for equipment.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.model_number
     *
     * @return the value of equipment.model_number
     *
     * @mbg.generated
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.model_number
     *
     * @param modelNumber the value for equipment.model_number
     *
     * @mbg.generated
     */
    public void setModelNumber(String modelNumber) {
        this.modelNumber = modelNumber == null ? null : modelNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.manufacturer
     *
     * @return the value of equipment.manufacturer
     *
     * @mbg.generated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.manufacturer
     *
     * @param manufacturer the value for equipment.manufacturer
     *
     * @mbg.generated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.attribute
     *
     * @return the value of equipment.attribute
     *
     * @mbg.generated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.attribute
     *
     * @param attribute the value for equipment.attribute
     *
     * @mbg.generated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.area_id
     *
     * @return the value of equipment.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.area_id
     *
     * @param areaId the value for equipment.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.band_width
     *
     * @return the value of equipment.band_width
     *
     * @mbg.generated
     */
    public String getBandWidth() {
        return bandWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.band_width
     *
     * @param bandWidth the value for equipment.band_width
     *
     * @mbg.generated
     */
    public void setBandWidth(String bandWidth) {
        this.bandWidth = bandWidth == null ? null : bandWidth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.port1
     *
     * @return the value of equipment.port1
     *
     * @mbg.generated
     */
    public Integer getPort1() {
        return port1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.port1
     *
     * @param port1 the value for equipment.port1
     *
     * @mbg.generated
     */
    public void setPort1(Integer port1) {
        this.port1 = port1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.port2
     *
     * @return the value of equipment.port2
     *
     * @mbg.generated
     */
    public Integer getPort2() {
        return port2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.port2
     *
     * @param port2 the value for equipment.port2
     *
     * @mbg.generated
     */
    public void setPort2(Integer port2) {
        this.port2 = port2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.port3
     *
     * @return the value of equipment.port3
     *
     * @mbg.generated
     */
    public Integer getPort3() {
        return port3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.port3
     *
     * @param port3 the value for equipment.port3
     *
     * @mbg.generated
     */
    public void setPort3(Integer port3) {
        this.port3 = port3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.port4
     *
     * @return the value of equipment.port4
     *
     * @mbg.generated
     */
    public Integer getPort4() {
        return port4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.port4
     *
     * @param port4 the value for equipment.port4
     *
     * @mbg.generated
     */
    public void setPort4(Integer port4) {
        this.port4 = port4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.handling_capacity1
     *
     * @return the value of equipment.handling_capacity1
     *
     * @mbg.generated
     */
    public String getHandlingCapacity1() {
        return handlingCapacity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.handling_capacity1
     *
     * @param handlingCapacity1 the value for equipment.handling_capacity1
     *
     * @mbg.generated
     */
    public void setHandlingCapacity1(String handlingCapacity1) {
        this.handlingCapacity1 = handlingCapacity1 == null ? null : handlingCapacity1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.handling_capacity2
     *
     * @return the value of equipment.handling_capacity2
     *
     * @mbg.generated
     */
    public String getHandlingCapacity2() {
        return handlingCapacity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.handling_capacity2
     *
     * @param handlingCapacity2 the value for equipment.handling_capacity2
     *
     * @mbg.generated
     */
    public void setHandlingCapacity2(String handlingCapacity2) {
        this.handlingCapacity2 = handlingCapacity2 == null ? null : handlingCapacity2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.function1
     *
     * @return the value of equipment.function1
     *
     * @mbg.generated
     */
    public String getFunction1() {
        return function1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.function1
     *
     * @param function1 the value for equipment.function1
     *
     * @mbg.generated
     */
    public void setFunction1(String function1) {
        this.function1 = function1 == null ? null : function1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.function2
     *
     * @return the value of equipment.function2
     *
     * @mbg.generated
     */
    public String getFunction2() {
        return function2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.function2
     *
     * @param function2 the value for equipment.function2
     *
     * @mbg.generated
     */
    public void setFunction2(String function2) {
        this.function2 = function2 == null ? null : function2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.function3
     *
     * @return the value of equipment.function3
     *
     * @mbg.generated
     */
    public String getFunction3() {
        return function3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.function3
     *
     * @param function3 the value for equipment.function3
     *
     * @mbg.generated
     */
    public void setFunction3(String function3) {
        this.function3 = function3 == null ? null : function3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.function4
     *
     * @return the value of equipment.function4
     *
     * @mbg.generated
     */
    public String getFunction4() {
        return function4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.function4
     *
     * @param function4 the value for equipment.function4
     *
     * @mbg.generated
     */
    public void setFunction4(String function4) {
        this.function4 = function4 == null ? null : function4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.function5
     *
     * @return the value of equipment.function5
     *
     * @mbg.generated
     */
    public String getFunction5() {
        return function5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.function5
     *
     * @param function5 the value for equipment.function5
     *
     * @mbg.generated
     */
    public void setFunction5(String function5) {
        this.function5 = function5 == null ? null : function5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.operator_id
     *
     * @return the value of equipment.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.operator_id
     *
     * @param operatorId the value for equipment.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.edit_time
     *
     * @return the value of equipment.edit_time
     *
     * @mbg.generated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.edit_time
     *
     * @param editTime the value for equipment.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", modelNumber=").append(modelNumber);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", attribute=").append(attribute);
        sb.append(", areaId=").append(areaId);
        sb.append(", bandWidth=").append(bandWidth);
        sb.append(", port1=").append(port1);
        sb.append(", port2=").append(port2);
        sb.append(", port3=").append(port3);
        sb.append(", port4=").append(port4);
        sb.append(", handlingCapacity1=").append(handlingCapacity1);
        sb.append(", handlingCapacity2=").append(handlingCapacity2);
        sb.append(", function1=").append(function1);
        sb.append(", function2=").append(function2);
        sb.append(", function3=").append(function3);
        sb.append(", function4=").append(function4);
        sb.append(", function5=").append(function5);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", editTime=").append(editTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}