package com.springboot.crm.entity;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.equipment_id
     *
     * @mbg.generated
     */
    private Integer equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.purchase_time
     *
     * @mbg.generated
     */
    private Date purchaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.using_customer_id
     *
     * @mbg.generated
     */
    private Integer usingCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.in_storage_time
     *
     * @mbg.generated
     */
    private Date inStorageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.in_storage_people_id
     *
     * @mbg.generated
     */
    private Integer inStoragePeopleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.out_storage_time
     *
     * @mbg.generated
     */
    private Date outStorageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.out_storage_people_id
     *
     * @mbg.generated
     */
    private Integer outStoragePeopleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.hardware_code
     *
     * @mbg.generated
     */
    private String hardwareCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.storage_area_id
     *
     * @mbg.generated
     */
    private Integer storageAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.edit_time
     *
     * @mbg.generated
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.edit_operater_id
     *
     * @mbg.generated
     */
    private Integer editOperaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.equipmentStatus
     *
     * @mbg.generated
     */
    private String equipmentstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.businessLevel
     *
     * @mbg.generated
     */
    private String businesslevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.equipment_id
     *
     * @return the value of goods.equipment_id
     *
     * @mbg.generated
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.equipment_id
     *
     * @param equipmentId the value for goods.equipment_id
     *
     * @mbg.generated
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.number
     *
     * @return the value of goods.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.number
     *
     * @param number the value for goods.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.purchase_time
     *
     * @return the value of goods.purchase_time
     *
     * @mbg.generated
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.purchase_time
     *
     * @param purchaseTime the value for goods.purchase_time
     *
     * @mbg.generated
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.using_customer_id
     *
     * @return the value of goods.using_customer_id
     *
     * @mbg.generated
     */
    public Integer getUsingCustomerId() {
        return usingCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.using_customer_id
     *
     * @param usingCustomerId the value for goods.using_customer_id
     *
     * @mbg.generated
     */
    public void setUsingCustomerId(Integer usingCustomerId) {
        this.usingCustomerId = usingCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.in_storage_time
     *
     * @return the value of goods.in_storage_time
     *
     * @mbg.generated
     */
    public Date getInStorageTime() {
        return inStorageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.in_storage_time
     *
     * @param inStorageTime the value for goods.in_storage_time
     *
     * @mbg.generated
     */
    public void setInStorageTime(Date inStorageTime) {
        this.inStorageTime = inStorageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.in_storage_people_id
     *
     * @return the value of goods.in_storage_people_id
     *
     * @mbg.generated
     */
    public Integer getInStoragePeopleId() {
        return inStoragePeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.in_storage_people_id
     *
     * @param inStoragePeopleId the value for goods.in_storage_people_id
     *
     * @mbg.generated
     */
    public void setInStoragePeopleId(Integer inStoragePeopleId) {
        this.inStoragePeopleId = inStoragePeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.out_storage_time
     *
     * @return the value of goods.out_storage_time
     *
     * @mbg.generated
     */
    public Date getOutStorageTime() {
        return outStorageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.out_storage_time
     *
     * @param outStorageTime the value for goods.out_storage_time
     *
     * @mbg.generated
     */
    public void setOutStorageTime(Date outStorageTime) {
        this.outStorageTime = outStorageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.out_storage_people_id
     *
     * @return the value of goods.out_storage_people_id
     *
     * @mbg.generated
     */
    public Integer getOutStoragePeopleId() {
        return outStoragePeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.out_storage_people_id
     *
     * @param outStoragePeopleId the value for goods.out_storage_people_id
     *
     * @mbg.generated
     */
    public void setOutStoragePeopleId(Integer outStoragePeopleId) {
        this.outStoragePeopleId = outStoragePeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.device_code
     *
     * @return the value of goods.device_code
     *
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.device_code
     *
     * @param deviceCode the value for goods.device_code
     *
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.hardware_code
     *
     * @return the value of goods.hardware_code
     *
     * @mbg.generated
     */
    public String getHardwareCode() {
        return hardwareCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.hardware_code
     *
     * @param hardwareCode the value for goods.hardware_code
     *
     * @mbg.generated
     */
    public void setHardwareCode(String hardwareCode) {
        this.hardwareCode = hardwareCode == null ? null : hardwareCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.storage_area_id
     *
     * @return the value of goods.storage_area_id
     *
     * @mbg.generated
     */
    public Integer getStorageAreaId() {
        return storageAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.storage_area_id
     *
     * @param storageAreaId the value for goods.storage_area_id
     *
     * @mbg.generated
     */
    public void setStorageAreaId(Integer storageAreaId) {
        this.storageAreaId = storageAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.operator_id
     *
     * @return the value of goods.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.operator_id
     *
     * @param operatorId the value for goods.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.edit_time
     *
     * @return the value of goods.edit_time
     *
     * @mbg.generated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.edit_time
     *
     * @param editTime the value for goods.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.edit_operater_id
     *
     * @return the value of goods.edit_operater_id
     *
     * @mbg.generated
     */
    public Integer getEditOperaterId() {
        return editOperaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.edit_operater_id
     *
     * @param editOperaterId the value for goods.edit_operater_id
     *
     * @mbg.generated
     */
    public void setEditOperaterId(Integer editOperaterId) {
        this.editOperaterId = editOperaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.equipmentStatus
     *
     * @return the value of goods.equipmentStatus
     *
     * @mbg.generated
     */
    public String getEquipmentstatus() {
        return equipmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.equipmentStatus
     *
     * @param equipmentstatus the value for goods.equipmentStatus
     *
     * @mbg.generated
     */
    public void setEquipmentstatus(String equipmentstatus) {
        this.equipmentstatus = equipmentstatus == null ? null : equipmentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.businessLevel
     *
     * @return the value of goods.businessLevel
     *
     * @mbg.generated
     */
    public String getBusinesslevel() {
        return businesslevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.businessLevel
     *
     * @param businesslevel the value for goods.businessLevel
     *
     * @mbg.generated
     */
    public void setBusinesslevel(String businesslevel) {
        this.businesslevel = businesslevel == null ? null : businesslevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", equipmentId=").append(equipmentId);
        sb.append(", status=").append(status);
        sb.append(", number=").append(number);
        sb.append(", purchaseTime=").append(purchaseTime);
        sb.append(", usingCustomerId=").append(usingCustomerId);
        sb.append(", inStorageTime=").append(inStorageTime);
        sb.append(", inStoragePeopleId=").append(inStoragePeopleId);
        sb.append(", outStorageTime=").append(outStorageTime);
        sb.append(", outStoragePeopleId=").append(outStoragePeopleId);
        sb.append(", deviceCode=").append(deviceCode);
        sb.append(", hardwareCode=").append(hardwareCode);
        sb.append(", storageAreaId=").append(storageAreaId);
        sb.append(", createTime=").append(createTime);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", editTime=").append(editTime);
        sb.append(", editOperaterId=").append(editOperaterId);
        sb.append(", equipmentstatus=").append(equipmentstatus);
        sb.append(", businesslevel=").append(businesslevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}