package com.springboot.crm.entity;

import java.io.Serializable;

public class SystemBillTotal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_bill_total.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_bill_total.system_bill
     *
     * @mbg.generated
     */
    private Integer systemBill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_bill_total.total_bill
     *
     * @mbg.generated
     */
    private Integer totalBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_bill_total
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_bill_total.id
     *
     * @return the value of system_bill_total.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_bill_total.id
     *
     * @param id the value for system_bill_total.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_bill_total.system_bill
     *
     * @return the value of system_bill_total.system_bill
     *
     * @mbg.generated
     */
    public Integer getSystemBill() {
        return systemBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_bill_total.system_bill
     *
     * @param systemBill the value for system_bill_total.system_bill
     *
     * @mbg.generated
     */
    public void setSystemBill(Integer systemBill) {
        this.systemBill = systemBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_bill_total.total_bill
     *
     * @return the value of system_bill_total.total_bill
     *
     * @mbg.generated
     */
    public Integer getTotalBill() {
        return totalBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_bill_total.total_bill
     *
     * @param totalBill the value for system_bill_total.total_bill
     *
     * @mbg.generated
     */
    public void setTotalBill(Integer totalBill) {
        this.totalBill = totalBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill_total
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", systemBill=").append(systemBill);
        sb.append(", totalBill=").append(totalBill);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}