package com.springboot.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemBillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public SystemBillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIsNull() {
            addCriterion("business_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIsNotNull() {
            addCriterion("business_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdEqualTo(Integer value) {
            addCriterion("business_customer_id =", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotEqualTo(Integer value) {
            addCriterion("business_customer_id <>", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdGreaterThan(Integer value) {
            addCriterion("business_customer_id >", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_customer_id >=", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdLessThan(Integer value) {
            addCriterion("business_customer_id <", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("business_customer_id <=", value, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdIn(List<Integer> values) {
            addCriterion("business_customer_id in", values, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotIn(List<Integer> values) {
            addCriterion("business_customer_id not in", values, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("business_customer_id between", value1, value2, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andBusinessCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("business_customer_id not between", value1, value2, "businessCustomerId");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalIsNull() {
            addCriterion("operator_charge_off_total is null");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalIsNotNull() {
            addCriterion("operator_charge_off_total is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalEqualTo(String value) {
            addCriterion("operator_charge_off_total =", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalNotEqualTo(String value) {
            addCriterion("operator_charge_off_total <>", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalGreaterThan(String value) {
            addCriterion("operator_charge_off_total >", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalGreaterThanOrEqualTo(String value) {
            addCriterion("operator_charge_off_total >=", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalLessThan(String value) {
            addCriterion("operator_charge_off_total <", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalLessThanOrEqualTo(String value) {
            addCriterion("operator_charge_off_total <=", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalLike(String value) {
            addCriterion("operator_charge_off_total like", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalNotLike(String value) {
            addCriterion("operator_charge_off_total not like", value, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalIn(List<String> values) {
            addCriterion("operator_charge_off_total in", values, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalNotIn(List<String> values) {
            addCriterion("operator_charge_off_total not in", values, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalBetween(String value1, String value2) {
            addCriterion("operator_charge_off_total between", value1, value2, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andOperatorChargeOffTotalNotBetween(String value1, String value2) {
            addCriterion("operator_charge_off_total not between", value1, value2, "operatorChargeOffTotal");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageIsNull() {
            addCriterion("customer_arrearage is null");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageIsNotNull() {
            addCriterion("customer_arrearage is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageEqualTo(String value) {
            addCriterion("customer_arrearage =", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageNotEqualTo(String value) {
            addCriterion("customer_arrearage <>", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageGreaterThan(String value) {
            addCriterion("customer_arrearage >", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageGreaterThanOrEqualTo(String value) {
            addCriterion("customer_arrearage >=", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageLessThan(String value) {
            addCriterion("customer_arrearage <", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageLessThanOrEqualTo(String value) {
            addCriterion("customer_arrearage <=", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageLike(String value) {
            addCriterion("customer_arrearage like", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageNotLike(String value) {
            addCriterion("customer_arrearage not like", value, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageIn(List<String> values) {
            addCriterion("customer_arrearage in", values, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageNotIn(List<String> values) {
            addCriterion("customer_arrearage not in", values, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageBetween(String value1, String value2) {
            addCriterion("customer_arrearage between", value1, value2, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andCustomerArrearageNotBetween(String value1, String value2) {
            addCriterion("customer_arrearage not between", value1, value2, "customerArrearage");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalIsNull() {
            addCriterion("finally_confirm_total is null");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalIsNotNull() {
            addCriterion("finally_confirm_total is not null");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalEqualTo(String value) {
            addCriterion("finally_confirm_total =", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalNotEqualTo(String value) {
            addCriterion("finally_confirm_total <>", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalGreaterThan(String value) {
            addCriterion("finally_confirm_total >", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalGreaterThanOrEqualTo(String value) {
            addCriterion("finally_confirm_total >=", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalLessThan(String value) {
            addCriterion("finally_confirm_total <", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalLessThanOrEqualTo(String value) {
            addCriterion("finally_confirm_total <=", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalLike(String value) {
            addCriterion("finally_confirm_total like", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalNotLike(String value) {
            addCriterion("finally_confirm_total not like", value, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalIn(List<String> values) {
            addCriterion("finally_confirm_total in", values, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalNotIn(List<String> values) {
            addCriterion("finally_confirm_total not in", values, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalBetween(String value1, String value2) {
            addCriterion("finally_confirm_total between", value1, value2, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andFinallyConfirmTotalNotBetween(String value1, String value2) {
            addCriterion("finally_confirm_total not between", value1, value2, "finallyConfirmTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonIsNull() {
            addCriterion("difference_reason is null");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonIsNotNull() {
            addCriterion("difference_reason is not null");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonEqualTo(String value) {
            addCriterion("difference_reason =", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonNotEqualTo(String value) {
            addCriterion("difference_reason <>", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonGreaterThan(String value) {
            addCriterion("difference_reason >", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonGreaterThanOrEqualTo(String value) {
            addCriterion("difference_reason >=", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonLessThan(String value) {
            addCriterion("difference_reason <", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonLessThanOrEqualTo(String value) {
            addCriterion("difference_reason <=", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonLike(String value) {
            addCriterion("difference_reason like", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonNotLike(String value) {
            addCriterion("difference_reason not like", value, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonIn(List<String> values) {
            addCriterion("difference_reason in", values, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonNotIn(List<String> values) {
            addCriterion("difference_reason not in", values, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonBetween(String value1, String value2) {
            addCriterion("difference_reason between", value1, value2, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andDifferenceReasonNotBetween(String value1, String value2) {
            addCriterion("difference_reason not between", value1, value2, "differenceReason");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("`time` is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("`time` is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("`time` =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("`time` <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("`time` >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`time` >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("`time` <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("`time` <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("`time` in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("`time` not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("`time` between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("`time` not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andSystemChargeIsNull() {
            addCriterion("system_charge is null");
            return (Criteria) this;
        }

        public Criteria andSystemChargeIsNotNull() {
            addCriterion("system_charge is not null");
            return (Criteria) this;
        }

        public Criteria andSystemChargeEqualTo(String value) {
            addCriterion("system_charge =", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeNotEqualTo(String value) {
            addCriterion("system_charge <>", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeGreaterThan(String value) {
            addCriterion("system_charge >", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeGreaterThanOrEqualTo(String value) {
            addCriterion("system_charge >=", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeLessThan(String value) {
            addCriterion("system_charge <", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeLessThanOrEqualTo(String value) {
            addCriterion("system_charge <=", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeLike(String value) {
            addCriterion("system_charge like", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeNotLike(String value) {
            addCriterion("system_charge not like", value, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeIn(List<String> values) {
            addCriterion("system_charge in", values, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeNotIn(List<String> values) {
            addCriterion("system_charge not in", values, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeBetween(String value1, String value2) {
            addCriterion("system_charge between", value1, value2, "systemCharge");
            return (Criteria) this;
        }

        public Criteria andSystemChargeNotBetween(String value1, String value2) {
            addCriterion("system_charge not between", value1, value2, "systemCharge");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_bill
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}