package com.springboot.crm.dao;

import com.springboot.crm.entity.BusinessCustomerHistoryInfo;
import com.springboot.crm.entity.BusinessCustomerHistoryInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface BusinessCustomerHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    long countByExample(BusinessCustomerHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int deleteByExample(BusinessCustomerHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int insert(BusinessCustomerHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int insertSelective(BusinessCustomerHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    List<BusinessCustomerHistoryInfo> selectByExample(BusinessCustomerHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    BusinessCustomerHistoryInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BusinessCustomerHistoryInfo record, @Param("example") BusinessCustomerHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BusinessCustomerHistoryInfo record, @Param("example") BusinessCustomerHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessCustomerHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_customer_history_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessCustomerHistoryInfo record);
}