package com.springboot.crm.dao;

import com.springboot.crm.entity.CheckGoodsRecords;
import com.springboot.crm.entity.CheckGoodsRecordsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface CheckGoodsRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    long countByExample(CheckGoodsRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int deleteByExample(CheckGoodsRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int insert(CheckGoodsRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int insertSelective(CheckGoodsRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    List<CheckGoodsRecords> selectByExample(CheckGoodsRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    CheckGoodsRecords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CheckGoodsRecords record, @Param("example") CheckGoodsRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CheckGoodsRecords record, @Param("example") CheckGoodsRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckGoodsRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_goods_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckGoodsRecords record);
}