package com.springboot.crm.dao;

import com.springboot.crm.entity.CustomerFollowUpRecord;
import com.springboot.crm.entity.CustomerFollowUpRecordExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface CustomerFollowUpRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    long countByExample(CustomerFollowUpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerFollowUpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int insert(CustomerFollowUpRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int insertSelective(CustomerFollowUpRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    List<CustomerFollowUpRecord> selectByExample(CustomerFollowUpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    CustomerFollowUpRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerFollowUpRecord record, @Param("example") CustomerFollowUpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerFollowUpRecord record, @Param("example") CustomerFollowUpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerFollowUpRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_follow_up_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerFollowUpRecord record);
}