package com.springboot.crm.dao;

import com.springboot.crm.entity.CustomerBusiness;
import com.springboot.crm.entity.CustomerBusinessExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CustomerBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    long countByExample(CustomerBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int insert(CustomerBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int insertSelective(CustomerBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    List<CustomerBusiness> selectByExample(CustomerBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    CustomerBusiness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerBusiness record, @Param("example") CustomerBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerBusiness record, @Param("example") CustomerBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerBusiness record);
}