package com.springboot.crm.dao;

import com.springboot.crm.entity.EditGoodsBefore;
import com.springboot.crm.entity.EditGoodsBeforeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface EditGoodsBeforeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    long countByExample(EditGoodsBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int deleteByExample(EditGoodsBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int insert(EditGoodsBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int insertSelective(EditGoodsBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    List<EditGoodsBefore> selectByExample(EditGoodsBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    EditGoodsBefore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EditGoodsBefore record, @Param("example") EditGoodsBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EditGoodsBefore record, @Param("example") EditGoodsBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EditGoodsBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edit_goods_before
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EditGoodsBefore record);
}