package com.springboot.crm.dao;

import com.springboot.crm.entity.EmployeeArea;
import com.springboot.crm.entity.EmployeeAreaExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EmployeeAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    long countByExample(EmployeeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int insert(EmployeeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    List<EmployeeArea> selectByExample(EmployeeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    EmployeeArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmployeeArea record, @Param("example") EmployeeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmployeeArea record, @Param("example") EmployeeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeArea record);
}