package com.springboot.crm.dao;

import com.springboot.crm.entity.EmployeeType;
import com.springboot.crm.entity.EmployeeTypeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EmployeeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    long countByExample(EmployeeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int insert(EmployeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    List<EmployeeType> selectByExample(EmployeeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    EmployeeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmployeeType record, @Param("example") EmployeeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmployeeType record, @Param("example") EmployeeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeType record);
}