package com.springboot.crm.dao;

import com.springboot.crm.entity.SystemBill;
import com.springboot.crm.entity.SystemBillExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface SystemBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    long countByExample(SystemBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int deleteByExample(SystemBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int insert(SystemBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int insertSelective(SystemBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    List<SystemBill> selectByExample(SystemBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    SystemBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemBill record, @Param("example") SystemBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemBill record, @Param("example") SystemBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemBill record);
}