package com.springboot.crm.dao;

import com.springboot.crm.entity.TotalBill;
import com.springboot.crm.entity.TotalBillExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface TotalBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    long countByExample(TotalBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int deleteByExample(TotalBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int insert(TotalBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int insertSelective(TotalBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    List<TotalBill> selectByExample(TotalBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    TotalBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TotalBill record, @Param("example") TotalBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TotalBill record, @Param("example") TotalBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TotalBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TotalBill record);
}