package com.springboot.crm.dao;

import com.springboot.crm.entity.TransactType;
import com.springboot.crm.entity.TransactTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TransactTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    long countByExample(TransactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int deleteByExample(TransactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int insert(TransactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int insertSelective(TransactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    List<TransactType> selectByExample(TransactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    TransactType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TransactType record, @Param("example") TransactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TransactType record, @Param("example") TransactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transact_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransactType record);
}